version: "2"
services:
  app:
    image: jc21/registry-ui
    ports:
      - 8082:80
    environment:
      - REGISTRY_HOST=:443
      - REGISTRY_SSL=true
      - REGISTRY_DOMAIN=:443
#      - REGISTRY_STORAGE_DELETE_ENABLED=
      - REGISTRY_USER=
      - REGISTRY_PASS=
    restart: on-failure
